// src/components/Education.svelte
<script lang="ts">
	// doing ts stuff here
</script>

<body>
	<h1><a id="education">Education</a></h1>
	<img src="unl-big.png" alt="University of Nebraska-Lincoln" width="210" height="70" /> <br />
	<br />
	<span>
		<strong>Attened: </strong> August 2013 - December 2020 <br />
		<strong>Bachelors:</strong> Arts and Science <br />
		<strong>Major: </strong> Computer Science <strong>Minor:</strong> Mathematics
	</span>
</body>

<style>
	/* doing css stuff here */
</style>

// components/Education.tsx
import Image from "next/image";
import { Space } from "antd";

import styles from "./Education.module.css"

const Education = () => {
    return (
        <div className={styles.body}>
            <h2><strong>Education</strong></h2>
            <Space direction="vertical" className={styles.space}>
                <Image src={"/unl-big.png"} height={70} width={210} layout={"fixed"} alt={"unl logo"} />
                <span>
                    <strong>Attened: </strong> August 2013 - December 2020 <br/>
                    <strong>Bachelors:</strong> Arts and Science <br/>
                    <strong>Major: </strong> Computer Science <strong>Minor:</strong> Mathematics
                </span>
            </Space>
        </div>
    )
}

export default Education;
