// components/AboutMe.tsx
import styles from './AboutMe.module.css'
import Image from "next/image";

const AboutMe = () => {
    return (
        <div className={styles.body}>
            <h2><strong>About Me</strong></h2>

            <Image src={"/jesse.jpeg"} height={150} width={150} layout={"intrinsic"} alt={"jesse"}></Image> <br/>
            <span><strong>Born:</strong> Red Bluff, CA April 16, 1995<br/>   
            <strong>From:</strong> Lincoln, NE USA 1999 - 2020<br/>   
            <strong>Current:</strong> Austin, TX USA 2021-Current</span><br/><br/>
        </div>
    )
}

export default AboutMe;

// src/components/Aboutme.svelte
<script lang="ts">
	// doing ts stuff here
</script>

<body>
	<h1><a id="aboutme">About Me</a></h1>
	<img src="jesse.jpeg" alt="Jesse R Cortes" width="200" height="200" /> <br /> <br />

	<span>
		<strong>Born:</strong> Red Bluff, CA April 16, 1995
		<br />
		<strong>From:</strong> Lincoln, NE USA 1999 - 2020
		<br />
		<strong>Current:</strong> Austin, TX USA 2021-Current
	</span>
	<br />
	<br />
</body>

<style>
	img {
		border-radius: 50%;
	}
</style>
